### ISSUE TITLE
function reevaluated even when no change in code dependency

### ISSUE THREAD

**Issue by martinResearch** [charmoniumQ/charmonium.cache#1]
Hi, thank you for this very useful library.

I noticed that sometimes a function get reevaluated from one run to another, even if the code source did not change.

Here is an example to reproduce:

```
from charmonium.cache import memoize

i = 1

def square(x):
    return x ** 2

@memoize()
def square_plus_one(x):
    print("recomputing")
    return square(x) + i


if __name__ == "__main__":
    square_plus_one(4)
```

Every once in a while (about every 5th call) it will recompute the function. Is that expected ?

**Comment by charmoniumQ** [comment]
Hello, sorry for the late response. I didn't notice this until now.

I have been actively developing the library quite a bit, and I cannot reproduce this behavior with the latest version. Let me know if you still have this problem and what version you are using.
